[package]
name = "ezlog_cli"
version = "0.1.0-dev"
edition = "2021"
description = "EZLog core function and code"
homepage = "https://github.com/s1rius/ezlog"
repository = "https://github.com/s1rius/ezlog"
license = "MIT OR Apache-2.0"
keywords = ["ezlog"]

[dependencies]
ezlog = {path = "../core"}