name: Build & Test

on:
  schedule:
    - cron: '30 0 * * *'

# push on dev for test
# on:
#   push:
#     branches:    
#       - dev

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "trace"

jobs:
  buid-test-check:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-11
          profile: minimal
          components: clippy
          default: true
          override: true
      - name: Build & Test - ezlog All Features
        run: cargo test --manifest-path ./ezlog-core/Cargo.toml --verbose --all-features --no-fail-fast
      - name: Build & Test - ezlog_cli
        run: cargo test --manifest-path ./ezlog-cli/Cargo.toml --verbose --no-default-features --no-fail-fast
      - name: Clippy Check
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy-${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --workspace  --all-features